apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbindings.binding.mysql.pivotal.io
spec:
  group: binding.mysql.pivotal.io
  names:
    kind: MysqlBinding
    listKind: MysqlBindingList
    plural: mysqlbindings
    singular: mysqlbinding
  scope: Namespaced
  version: v1alpha1
